# Dependecies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Prepare the Dataset

In [16]:
df = pd.read_csv('Data/ultimate_student_productivity_dataset_5000.csv')
df.drop('student_id', axis=1, inplace=True)
df.head(2)

,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,18,Other,High School,7.64,1.56,2.2,3.05,2.19,6.52,6.47,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,18,Other,High School,2.21,2.22,2.1,1.65,2.55,5.97,6.05,111,339,0,0,Good,3,15.92,37.00,13.70,1.00

In [17]:
target_col = "gender"

categorical_cols = ["gender", "academic_level", "internet_quality"]
binary_cols = ["part_time_job", "upcoming_deadline"]

numeric_cols = [
    "age", "study_hours", "self_study_hours", "online_classes_hours",
    "social_media_hours", "gaming_hours", "sleep_hours",
    "screen_time_hours", "exercise_minutes", "caffeine_intake_mg",
    "mental_health_score", "focus_index", "burnout_level", "exam_score"
]

In [18]:
# 3. Ordinal Encoding
academic_map = {'High School': 0, 'Undergraduate': 1, 'Postgraduate': 2}
internet_map = {'Poor': 0, 'Average': 1, 'Good': 2}
df['academic_level'] = df['academic_level'].map(academic_map)
df['internet_quality'] = df['internet_quality'].map(internet_map)
gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
df['gender'] = df['gender'].map(gender_map)

# Use this for Linear Regression
# df = pd.get_dummies(df, columns=['gender'], prefix='gender', dtype=int, drop_first=True)
# df = pd.get_dummies(df, columns=["gender","academic_level","internet_quality"], drop_first=True)

In [19]:
df

,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,18,2,0,7.64,1.56,2.20,3.05,2.19,6.52,6.47,81,38,1,0,2,10,43.05,31.77,73.65,50.16
1,18,2,0,2.21,2.22,2.10,1.65,2.55,5.97,6.05,111,339,0,0,2,3,15.92,37.00,13.70,1.00
2,22,0,0,3.45,0.00,0.29,1.34,2.08,8.39,7.62,68,266,0,1,2,8,27.39,34.37,45.15,18.30
3,17,2,0,5.75,2.08,3.01,2.27,2.20,6.31,11.67,113,480,1,1,0,3,22.31,77.31,20.92,9.37
4,19,2,0,6.83,1.72,3.33,2.65,0.70,8.01,10.02,121,24,1,0,2,8,38.11,39.53,59.23,27.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,2,1,3.93,1.42,0.54,2.58,2.62,9.30,6.38,113,496,0,0,2,9,35.55,33.24,48.83,22.51
4996,24,0,0,4.00,0.00,3.00,4.45,2.47,6.42,7.32,146,411,0,1,0,5,16.87,59.07,23.32,2.00
4997,22,0,1,5.63,2.52,2.89,3.58,1.07,6.65,9.51,123,306,0,1,2,7,23.85,47.72,41.09,27.89
4998,17,0,1,3.58,2.83,1.53,5.88,1.28,7.36,8.31,54,304,1,1,2,4,13.04,58.90,12.62,3.63
4999,22,2,1,5.60,4.14,2.17,3.05,2.74,6.38,9.59,24,219,0,1,2,3,29.98,61.01,34.72,10.76

In [20]:
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set: {X_train.shape[0]} samples")
print(f"Testing set: {X_test.shape[0]} samples")

Training set: 4000 samples
Testing set: 1000 samples

In [21]:
scaler = StandardScaler()

# Fit ONLY on training numeric columns
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

# Transform test numeric columns using train statistics
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [22]:
X_train_array = X_train.to_numpy()
y_train_array = y_train.to_numpy().reshape(-1, 1)

X_test_array = X_test.to_numpy()
y_test_array = y_test.to_numpy().reshape(-1, 1)


print("shape of X train: ",X_train_array.shape)
print('Shape of y train: ',y_train_array.shape)

print("shape of X test: ",X_test_array.shape)
print('Shape of y test: ',y_test_array.shape)

shape of X train:  (4000, 19)
Shape of y train:  (4000, 1)
shape of X test:  (1000, 19)
Shape of y test:  (1000, 1)

In [ ]:
class LogisticRegression:
    def __init__(self, learning_rate = .0001, iterations = 10000):
        self.lr = learning_rate
        self.iteratiosn = iterations
        self.weights = None
        self.bias = None

    
    def compute_gradient(self):
        pass

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self,X,y):
        n_samples, n_features = X.shape
        self.weights = np.ones((n_features,1))
        self.bias = 0
        z  = X@self.weights + self.bias
        y_pred = self.sigmoid(z)

SyntaxError: invalid syntax (2678991014.py, line 1)